$vars = @{
    "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" = "pk_live_51SvQpPII04nd8gjIxX2k1cZ6K4MxtF5sX6lneq8JIBpKi9OgA1vagumUQLeAdbQbG5WQOYcRZy8GomfXs8Z1uSVQ00k1qOi230"
    "NEXT_PUBLIC_STRIPE_PRICE_WEB_IDENTITY" = "price_1TXsQyII04nd8gjINrsY2WCM"
    "NEXT_PUBLIC_STRIPE_PRICE_WEB_GROWTH" = "price_1TXsRnII04nd8gjIYgeumLe4"
    "NEXT_PUBLIC_STRIPE_PRICE_WEB_ENTERPRISE" = "price_1TXsSIIII04nd8gjIWXrbEM4"
    "NEXT_PUBLIC_STRIPE_PRICE_MANAGEMENT" = "price_1TXsSyII04nd8gjIaeAiDT0K"
    "NEXT_PUBLIC_STRIPE_PRICE_POD_BROADCASTER" = "price_1TXsTWII04nd8gjId5Rt9X74"
    "NEXT_PUBLIC_STRIPE_PRICE_POD_GROWTH" = "price_1TXsTxII04nd8gjINbPs1Ul8"
    "NEXT_PUBLIC_STRIPE_PRICE_POD_SYNDICATION" = "price_1TXsUYII04nd8gjIft1PCRx2"
    "NEXT_PUBLIC_STRIPE_PRICE_PROD_FIELD" = "price_1TXsV6II04nd8gjIpZJ0GSiR"
    "NEXT_PUBLIC_STRIPE_PRICE_PROD_LIVE" = "price_1TXsVeII04nd8gjIKxlaT1DK"
    "NEXT_PUBLIC_STRIPE_PRICE_PROD_PROTOCOL" = "price_1TXsWBII04nd8gjIzzT5bsNf"
    "NEXT_PUBLIC_STRIPE_PRICE_PROD_AUTHORITY" = "price_1TXsWkII04nd8gjILJzltgV7"
    "NEXT_PUBLIC_STRIPE_PRICE_SOCIAL_MICRO" = "price_1TXsXNII04nd8gjI1PUWPhRo"
    "NEXT_PUBLIC_STRIPE_PRICE_SOCIAL_VELOCITY" = "price_1TXsY9II04nd8gjIIqHx1x4x"
    "NEXT_PUBLIC_STRIPE_PRICE_BRANDING" = "price_1TXsYiII04nd8gjITnSN7WRI"
    "NEXT_PUBLIC_STRIPE_PRICE_AUDIT" = "price_1TXsZFIJM04nd8gjIYswjGpwG"
    "NEXT_PUBLIC_STRIPE_PRICE_TECH" = "price_1TXsa4II04nd8gjIqDYIPS1T"
    "NEXT_PUBLIC_STRIPE_PRICE_MARKET_TAKEOVER" = "price_1TXsapII04nd8gjIdHMTCFMb"
    "NEXT_PUBLIC_STRIPE_PRICE_INSTALLMENT_BESPOKE" = "price_1TXsbNII04nd8gjIAO4opzu8"
    "NEXT_PUBLIC_STRIPE_PRICE_RECURRING_BESPOKE" = "price_1TXscBII04nd8gjIlyItbFw9"
    "NEXT_PUBLIC_STRIPE_PRICE_FOUNDERS_GROWTH" = "price_1TXscoII04nd8gjI6HPYpqIc"
}

foreach ($key in $vars.Keys) {
    Write-Host "Setting $key..." -ForegroundColor Cyan
    npx netlify env:set $key $vars[$key] --context production
}

Write-Host "`nDone! All 21 Stripe variables pushed to Netlify (production only)." -ForegroundColor Green
