
import fs from 'fs';
import path from 'path';
import OpenAI from 'openai';
import { GEAR_COLLECTION, GearItem } from '../src/data/gear';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load environment variables from .env.local
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

async function generateDossier(item: GearItem): Promise<string> {
    console.log(`\n🤖 Processing Sentinel Protocol for: ${item.name} (${item.id})...`);

    const systemPrompt = `
You are the Lead Technical Architect for the Power Digital Media Showroom.
Your aesthetic is "Cyberpunk Professional". High-tech, authoritative, slightly cynical but ultimately business-focused.

MISSION: Generate a "Technical Intelligence Dossier" for the following product.

PRODUCT: ${item.name} (${item.brand})
CATEGORY: ${item.category}
LEVEL: ${item.level}
CONTEXT: ${item.description} ${item.longDescription || ''}

STRICT ARCHITECTURAL RULES:
1. Do NOT use: "delve", "tapestry", "landscape", "navigate", "unlock the potential", "game-changer", "rapidly evolving world".
2. Format as Markdown.
3. Use the exact headers detailed below.

OUTPUT FORMAT:

## TECHNICAL INTELLIGENCE DOSSIER

### RECOMMENDATION LOGIC
[Why do we recommend this? Cite technical benchmarks (TFLOPS, SPL, Bit-depth) and ROI. Use the phrase "The Power Digital Recommendation Protocol".]

### COMMUNITY INTEL
[Deep Scrape: Summarize the "vibe" from r/hardware, r/audioengineering, etc. Identify one common technical quirk/failure point and one "pro-user" optimization.]

### PERSONA CONFLICT PROTOCOL
**The Senior Engineer:** [A "No-Nonsense" cynical take on limitations/price.]
**The Strategist:** [Justify the purchase as a 24-month business asset.]
`;

    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-4o",
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: "Execute Dossier Generation." }
            ],
            temperature: 0.7,
        });

        return completion.choices[0].message.content || "";
    } catch (error) {
        console.error(`❌ Error generating content for ${item.id}:`, error);
        return "";
    }
}

async function main() {
    console.log("🚀 Starting Showroom Sentinel Content Injection...");

    const updatedCollection: GearItem[] = [];
    let modifiedCount = 0;

    for (const item of GEAR_COLLECTION) {
        if (item.technicalDossier) {
            console.log(`✅ Dossier already exists for: ${item.name}`);
            updatedCollection.push(item);
            continue;
        }

        const dossier = await generateDossier(item);
        if (dossier) {
            updatedCollection.push({ ...item, technicalDossier: dossier });
            modifiedCount++;
        } else {
            updatedCollection.push(item);
        }

        // Sleep specifically to avoid rate limits if massive
        await new Promise(resolve => setTimeout(resolve, 1000));
    }

    if (modifiedCount > 0) {
        console.log(`\n💾 Injecting ${modifiedCount} new dossiers into gear.ts...`);

        const fileContent = `
// AUTO-GENERATED BY SHOWROOM SENTINEL PROTOCOL
// DO NOT EDIT MANUALLY IF YOU WANT TO PRESERVE FORMATTING PERMANENTLY without checking script logic

export interface GearItem {
    id: string;
    asin?: string;
    name: string;
    brand: string;
    category: 'Audio' | 'PC' | 'Visual' | 'Lighting' | 'Build Kits' | 'Monitors' | 'Essentials';
    useCase?: 'Streaming' | 'Editing' | 'Podcasting' | 'All-in-One' | 'Gaming';
    level?: 'Entry' | 'Pro' | 'Elite';
    description: string;
    longDescription?: string;
    features?: string[];
    technicalSpecs: string[];
    priceRange: string;
    image: string;
    amazonLink: string;
    subCategory?: string;
    isFeatured?: boolean;
    whatIsInTheBox?: string[];
    ourTake?: string;
    seoTags?: string[];
    pros?: string[];
    cons?: string[];
    deploymentScenario?: string;
    technicalDossier?: string;
}

export const GEAR_COLLECTION: GearItem[] = ${JSON.stringify(updatedCollection, null, 4)};
`;

        fs.writeFileSync(path.resolve(__dirname, '../src/data/gear.ts'), fileContent.trim());
        console.log("✅ Operation Complete. gear.ts updated.");
    } else {
        console.log("✨ No new content needed.");
    }
}

main();
