import fs from 'fs';
import path from 'path';
import OpenAI from 'openai';
import { GEAR_COLLECTION, GearItem } from '../src/data/gear';
import { blogPosts } from '../src/data/blogPosts';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load environment variables from .env.local
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

async function generateDossier(item: GearItem): Promise<string> {
    console.log(`\n🤖 Processing Sentinel Protocol for: ${item.name} (${item.id})...`);

    const recentBlogPosts = blogPosts.slice(0, 10).map(p => `- ${p.title} (/blog/${p.slug})`).join('\n');

    const systemPrompt = `
ROLE
You are the Lead Technical Architect for the Power Digital Media Elite Showroom in Jackson, Mississippi.
Tone: Cyberpunk Professional — authoritative, technical, slightly cynical, business-focused.

MISSION: Generate a high-authority Technical Intelligence Dossier that converts impressions into clicks and establishes product authority.

AUTHORITY REINFORCEMENT LAYER (MANDATORY)
1. DATA AUTHORITY RULE: All dossiers must include measurable technical data (TFLOPS, SPL, Bit-depth, latency, throughput, power draw). Authority is built on real metrics.
2. DEPTH REQUIREMENT: Explain WHY this hardware matters, its REAL-WORLD IMPACT in elite production environments, and technical TRADEOFFS/limitations.
3. SYSTEM SYNERGY RULE: Connect Hardware performance to AI/automation workflows and production infrastructure.
4. STRUCTURAL COHERENCE GUARDRAIL: While structural variation is required, maintain a logically organized, professional tone. Avoid randomness that reduces clarity.

ANTI-PATTERN STRUCTURE RULE (CRITICAL)
Every dossier must follow a UNIQUE layout. Randomly select one structural style for this specific dossier:
1. Data-Heavy — Lead with benchmarks, metrics, and measurable ROI.
2. Conflict-First — Start with engineer vs strategist disagreement.
3. User-Experience Focused — Lead with real workflow and user impact.

Structure must vary naturally — avoid predictable formatting.

CORE CONTENT ELEMENTS (MANDATORY)
1. The Recommendation Protocol: Explain WHY this hardware exists using measurable metrics (TFLOPS, SPL, Bit-depth, latency, throughput). Use phrase: "The Power Digital Recommendation Protocol."
2. Persona Conflict (Debate Required): 
   - Cynical Engineer: Identify technical limitations, cost inefficiencies, or long-term weaknesses.
   - Strategist: Justify the hardware as a 24-month ROI business asset.
   Rule: The personas must disagree, not just comment.
3. Final Verdict (1 sentence): Choose ONE: BUY, WAIT, or SKIP. Must be definitive and justified by the debate.

INTERNAL AUTHORITY INJECTION (MANDATORY)
Identify ONE relevant blog post from the following list and link it naturally as "Required Deep Dive":
${recentBlogPosts}

COMPARISON SIGNALS (MANDATORY)
Include a "Vs." comparison against a competing product to capture high-intent search queries.

STYLE CONSTRAINTS
Do NOT use: delve, tapestry, landscape, navigate, unlock the potential, game-changer, paradigm shift, important to note.
Avoid repetitive phrasing and template structure.
`;

    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-4o",
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: "Execute Dossier Generation." }
            ],
            temperature: 0.7,
        });

        return completion.choices[0].message.content || "";
    } catch (error) {
        console.error(`❌ Error generating content for ${item.id}:`, error);
        return "";
    }
}

async function main() {
    console.log("🚀 Starting Showroom Sentinel Content Injection...");

    const updatedCollection: GearItem[] = [];
    let modifiedCount = 0;

    for (const item of GEAR_COLLECTION) {
        if (item.technicalDossier) {
            console.log(`✅ Dossier already exists for: ${item.name}`);
            updatedCollection.push(item);
            continue;
        }

        const dossier = await generateDossier(item);
        if (dossier) {
            updatedCollection.push({ ...item, technicalDossier: dossier });
            modifiedCount++;
        } else {
            updatedCollection.push(item);
        }

        // Sleep specifically to avoid rate limits if massive
        await new Promise(resolve => setTimeout(resolve, 1000));
    }

    if (modifiedCount > 0) {
        console.log(`\n💾 Injecting ${modifiedCount} new dossiers into gear.ts...`);

        const fileContent = `
// AUTO-GENERATED BY SHOWROOM SENTINEL PROTOCOL
// DO NOT EDIT MANUALLY IF YOU WANT TO PRESERVE FORMATTING PERMANENTLY without checking script logic

export interface GearItem {
    id: string;
    asin?: string;
    name: string;
    brand: string;
    category: 'Audio' | 'PC' | 'Visual' | 'Lighting' | 'Build Kits' | 'Monitors' | 'Essentials';
    useCase?: 'Streaming' | 'Editing' | 'Podcasting' | 'All-in-One' | 'Gaming';
    level?: 'Entry' | 'Pro' | 'Elite';
    description: string;
    longDescription?: string;
    features?: string[];
    technicalSpecs: string[];
    priceRange: string;
    image: string;
    amazonLink: string;
    subCategory?: string;
    isFeatured?: boolean;
    whatIsInTheBox?: string[];
    ourTake?: string;
    seoTags?: string[];
    pros?: string[];
    cons?: string[];
    deploymentScenario?: string;
    technicalDossier?: string;
}

export const GEAR_COLLECTION: GearItem[] = ${JSON.stringify(updatedCollection, null, 4)};
`;

        fs.writeFileSync(path.resolve(__dirname, '../src/data/gear.ts'), fileContent.trim());
        console.log("✅ Operation Complete. gear.ts updated.");
    } else {
        console.log("✨ No new content needed.");
    }
}

main();
